In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(np.zeros(10))
print(np.zeros((3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
print(np.arange(5))
print(np.arange(2, 9))
print(np.arange(5, 8, 0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [8]:
a = np.array([1, 2, 3, 4, 5])
b = a * 2
print(b)

[ 2  4  6  8 10]


In [10]:
x = np.arange(10)
y = 3 * x + 5
print(y)

[ 5  8 11 14 17 20 23 26 29 32]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b.shape)

(2, 3)
(3, 3)


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a =', a)
b = a.flatten()
print('b =', b)

a = [[1 2 3]
 [4 5 6]]
b = [1 2 3 4 5 6]


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = v[0]
b = v[1:]
c = v[:, 0]
print('a =', a)
print('b =', b)
print('c =', c)

a = [1 2 3]
b = [[4 5 6]
 [7 8 9]]
c = [1 4 7]
